print("Please enter a character for the eye !")
eye = input()
print("Beeps expression is now as follows:\n")
print("#######")
print("# " + eye +" "+eye+" #" )
print("#     #")
print("# ### #")
print("#     #")
print("#######")